POST http://localhost:5000/register HTTP/1.3
Content-Type: application/json

{
	"name": "Paulo Henrique",
	"phoneNumber": "33991158180",
	"email": "teste@email.com",
	"password": "teste123",
	"plan": "exclusive"
}

###
POST http://localhost:5000/login HTTP/1.3
Content-Type: application/json

{
	"email": "teste@email.com",
	"password": "teste123"
}