services:  
  mongodb:
    container_name: event-facil-mongodb
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: docker
      MONGODB_INITDB_ROOT_PASSWORD: docker 